add_library(lotus MODULE lotus.cpp ${fcitx_lotus_core_sources})
set_target_properties(lotus PROPERTIES OUTPUT_NAME "lotus")
set_target_properties(lotus PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_link_options(lotus PRIVATE "-Wl,-exclude-libs,ALL")
target_link_libraries(lotus
	Fcitx5::Core
	Fcitx5::Config
  Fcitx5::Module::Emoji
	Bamboo::Core
	Pthread::Pthread
)

target_include_directories(lotus PRIVATE
    ${PROJECT_BINARY_DIR}
)
target_compile_definitions(lotus PRIVATE
    FCITX5_LOTUS_SETTINGS_PATH=\"${CMAKE_INSTALL_FULL_BINDIR}/fcitx5-lotus-settings\"
    FCITX_LOTUS_ICON_DIR=\"${CMAKE_INSTALL_FULL_DATADIR}/icons/hicolor/scalable/apps\"
)
install(TARGETS lotus DESTINATION "${CMAKE_INSTALL_LIBDIR}/fcitx5")

fcitx5_translate_desktop_file(lotus.conf.in lotus.conf)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/lotus.conf" DESTINATION "${CMAKE_INSTALL_DATADIR}/fcitx5/inputmethod")
configure_file(lotus-addon.conf.in.in lotus-addon.conf.in)
fcitx5_translate_desktop_file("${CMAKE_CURRENT_BINARY_DIR}/lotus-addon.conf.in" lotus-addon.conf)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/lotus-addon.conf" RENAME lotus.conf DESTINATION "${FCITX_INSTALL_PKGDATADIR}/addon")
